### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by maxpipoka** [Ness733/Misiotronica#1]
Hola Nestor. Estuve revisando tu proyecto y esta muy bueno.
Tengo de momento algunas observaciones relacionadas con el estilado.
En la pagina de contacto al enviar el mensaje, aparece un modal avisando del success del envio, El boton de cerrar ese modal, esta desalineada la X.
Despues el menú lateral proba tenerlo unos pixeles mas hacia la izquierda, de momento se ve un bordecito emergiendo ademas del burger button.

Ya poniéndome técnico, podrías sacar la fuente de la lista de artículos fuera de la estructura de los componentes, en un repositorio digamos. En un sistema real ese módulo se encargaría de la obtención de los datos desde una db y los pondría a disposición exportandolos. De esta manera abstraes los modulos separando responsabilidades.

Con lo de Redux y el estado global entiendo que es una feature todavía en desarrollo.

**Comment by Ness733** [comment]
Hola Martín, gracias por tu revisión! Tal cuál, me hubiese gustado entender el tema de bases de datos para poder implementarlo, ya que sería lo que terminaria de convertir el proyecto en algo más real en cuestiones técnicas. 

Con el tema de la X en el modal de la página de contacto. Te voy a adjuntar unas screens porque en mi caso se ve alineada la X. No sé bien en qué dirección corregirlo o cómo replicarlo. Si me podrias enviar una captura de cómo se ve desde tu lado te lo agradeceria. Saludos!

https://cdn.discordapp.com/attachments/1101020125643153488/1136019370301214741/image.png
https://media.discordapp.net/attachments/1101020125643153488/1136018367346643154/image.png

**Comment by maxpipoka** [comment]
Copiado Nestor, en un rato me fijo a ver que puede ser. Y te paso captura.

**Comment by maxpipoka** [comment]
Solucionado lo del css.

Para desacoplar responsabilidades sacar fuera de componentes el módulo de redux y en un repository ponel la lista de productos.
Ahí iría la lógica de comunicación con la DDBB.
